# Generated by Django 4.1.7 on 2023-03-25 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abortiondata',
            old_name='state',
            new_name='zips',
        ),
    ]
