# Generated by Django 4.1.7 on 2023-03-25 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_state_abortiondata_zips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abortiondata',
            old_name='zips',
            new_name='state',
        ),
    ]
