# Generated by Django 4.1.7 on 2023-03-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_zips_abortiondata_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abortiondata',
            name='policy',
            field=models.TextField(null=True),
        ),
    ]
