# Generated by Django 4.1.7 on 2023-03-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_state_alter_abortiondata_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abortiondata',
            name='state',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
